name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  tests-and-coverage:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run unit tests
        run: make test

      - name: Validate coverage threshold
        run: make coverage
